### ISSUE TITLE
Application names do not appear in the Alerts Dashboard Nerdpack 

### ISSUE THREAD

**Issue by esmeNR** [newrelic-experimental/nr1-alerts-board#14]
I cloned this nerdpack but in any account that clones it, the names of the applications do not appear
![Captura de pantalla de 2021-11-29 19-01-03](https://user-images.githubusercontent.com/89275724/144078522-50edc562-d014-41f9-817e-1bd3b2e98999.png)

**Comment by abhisheklad** [comment]
Thanks for creating the issue. Will be fixed in next release. @esmeNR
